### ISSUE TITLE
What is your keras version and tensorflow version?

### ISSUE THREAD

**Issue by pengzhangzhi** [UNIMIBInside/Smart-Mobility-Prediction#5]
Hi,  
Thank you for your repo. It is such a huge contribution for the field of traffic prediction. 
However when I run this repo in my own computer, a lots of errors came,  so I want to know your keras version,tensorflow version, and cuda verison.

**Comment by Robyt96** [comment]
Hi!
Thank you for appreciating our work. We used tensorflow 2.4.1 and keras 2.4.3. We run the most part of our experiments on Google Colab with GPU hardware acceleration.
